import { NextResponse } from "next/server";
import { connectDB } from "@/app/lib/mongo";
import nodemailer from "nodemailer";

export async function GET() {
  try {
    const db = await connectDB();

    const today = new Date();
    const day = today.getDay();
    const diffToMonday = day === 0 ? -6 : 1 - day;

    const start = new Date(today);
    start.setDate(today.getDate() + diffToMonday);
    start.setHours(0, 0, 0, 0);

    const end = new Date(start);
    end.setDate(start.getDate() + 6);
    end.setHours(23, 59, 59, 999);

    const tasks = await db
      .collection("tasks")
      .find(
        { status: "completed", createdAt: { $gte: start, $lte: end } },
        { projection: { name: 1, _id: 0 } }
      )
      .toArray();

    const names = tasks.map((t) => t.name);

    const rows = names
      .map(
        (task, i) => `
        <tr>
          <td style="padding:10px;border:1px solid #ddd;text-align:center;">${i + 1}</td>
          <td style="padding:10px;border:1px solid #ddd;">${task}</td>
        </tr>
      `
      )
      .join("");

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    await transporter.sendMail({
      from:`"TaskTrail" <${process.env.MAIL_USER}>`,
      to: "amith10mnr@gmail.com",
      subject: "Weekly Task Report",
      html: `
      <div style="font-family:Arial,sans-serif;max-width:650px;margin:auto;">
        
         <img
    src="https://sst-task-trail.vercel.app/TaskTrail-Logo.png"
    alt="Task Report"
    style="display:block;margin:20px auto;max-width:200px;width:100%;border-radius:8px;"
  >


         <h2 style="color:#2c3e50;"><b>Weekly Task Report</b></h2>

        <p>
          <b>Hello,</b><br><br>
          Here is the <b>summary of tasks completed this week by your intern.</b>
        </p>

        <p><b>Total Tasks Completed:</b> ${names.length}</p>

        <table style="width:100%;border-collapse:collapse;margin-top:15px;">
          <thead>
            <tr style="background:#f2f2f2;">
              <th style="padding:10px;border:1px solid #ddd;"><b>#</b></th>
              <th style="padding:10px;border:1px solid #ddd;"><b>Task Name</b></th>
            </tr>
          </thead>
          <tbody>
            ${rows}
          </tbody>
        </table>

         <p style="margin-top:25px;font-size:12px;color:#777;">
           For detailed view, please visit <a href="https://sst-task-trail.vercel.app/dashboard" style="color:#3498db;text-decoration:none;">TaskTrail Dashboard</a>.
        </p>

        <p style="margin-top:5px;font-size:12px;color:#777;">
          <b>Note:</b> This is an automated weekly report generated by TaskTrail.
        </p>

      </div>
      `,
    });

    return NextResponse.json({ message: "Report sent successfully" });
  } catch (error: any) {
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}